-- MySQL Script generated by MySQL Workbench
-- mar. 09 avril 2019 12:29:27 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Meteo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Meteo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Meteo` DEFAULT CHARACTER SET utf8 ;
USE `Meteo` ;

-- -----------------------------------------------------
-- Table `Meteo`.`Station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Meteo`.`Station` (
  `idStation` INT(3) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `batterie` VARCHAR(3) NULL,
  PRIMARY KEY (`idStation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meteo`.`TemperatureHumidite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Meteo`.`TemperatureHumidite` (
  `horodatage` DATETIME NOT NULL,
  `temperature` DECIMAL NULL,
  `humidite` INT(3) NULL,
  `idStation` INT(3) NOT NULL,
  PRIMARY KEY (`horodatage`, `idStation`),
  UNIQUE INDEX `horodatage_UNIQUE` (`horodatage` ASC),
  INDEX `fk_TemperatureHumidite_Station1_idx` (`idStation` ASC),
  CONSTRAINT `fk_TemperatureHumidite_Station1`
    FOREIGN KEY (`idStation`)
    REFERENCES `Meteo`.`Station` (`idStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meteo`.`Vent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Meteo`.`Vent` (
  `horodatage` INT NOT NULL,
  `vitesse` DECIMAL NULL,
  `direction` INT(3) NULL,
  `rafale` DECIMAL NULL,
  `idStation` INT(3) NOT NULL,
  PRIMARY KEY (`horodatage`, `idStation`),
  INDEX `fk_Vent_Station_idx` (`idStation` ASC),
  CONSTRAINT `fk_Vent_Station`
    FOREIGN KEY (`idStation`)
    REFERENCES `Meteo`.`Station` (`idStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meteo`.`Pluie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Meteo`.`Pluie` (
  `horodatage` DATETIME NOT NULL,
  `quantite` DECIMAL NULL,
  `idStation` INT(3) NOT NULL,
  PRIMARY KEY (`horodatage`, `idStation`),
  INDEX `fk_Pluie_Station1_idx` (`idStation` ASC),
  CONSTRAINT `fk_Pluie_Station1`
    FOREIGN KEY (`idStation`)
    REFERENCES `Meteo`.`Station` (`idStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
